const SET_YEAR = 'SET_YEAR'
const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST'
const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS'
const GET_PHOTOS_FAIL = 'GET_PHOTOS_FAIL'
const LOGIN_REQUEST = 'LOGIN_REQUEST'
const LOGIN_CHECK = 'LOGIN_CHECK'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAIL = 'LOGIN_FAIL'
const LOGIN_NEEDED = 'LOGIN_NEEDED'

export default {
  SET_YEAR,
  GET_PHOTOS_REQUEST,
  GET_PHOTOS_SUCCESS,
  GET_PHOTOS_FAIL,
  LOGIN_REQUEST,
  LOGIN_CHECK,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  LOGIN_NEEDED,
}
